### PR TITLE
Implement the core functionality of ruby agent tracing

### PR DESCRIPTION
**Pull request by CodePrometheus**
# Test Report
image

image

For Segment Data side
```
traceId: "842b36d3180241abae4d7329f8d65c71"
traceSegmentId: "d348f0d8d5db4132a66a836340e8bf25"
spans {
  spanId: 1
  startTime: 1735206158638
  endTime: 1735206158641
  operationName: "Redis/SET"
  peer: "localhost:6379"
  spanType: Exit
  spanLayer: Cache
  componentId: 7
  tags {
    key: "db.type"
    value: "Redis"
    }
}
spans {
  spanId: 2
  startTime: 1735206158641
  endTime: 1735206158643
  operationName: "Redis/GET"
  peer: "localhost:6379"
  spanType: Exit
  spanLayer: Cache
  componentId: 7
  tags {
    key: "db.type"
    value: "Redis"
    }
}
spans {
  parentSpanId: -1
  startTime: 1735206158637
  endTime: 1735206158645
  operationName: "/hello/sw"
  peer: "127.0.0.1:4567"
  spanLayer: Http
  componentId: 12001
  tags {
    key: "http.method"
    value: "GET"
    }
  tags {
    key: "http.url"
    value: "/hello/sw"
    }
}
service: "Your_ApplicationName"
serviceInstance: "Your_InstanceName"
```

### CODE REVIEW

**Comment by wu-sheng** [comment]
Cool, have you verified topology and metrics as well?

**Review by wu-sheng — DISMISSED** [review]

**Comment by CodePrometheus** [comment]
> Cool, have you verified topology and metrics as well?

It works.
image

image

**Review by wu-sheng — DISMISSED** [review]

**Comment by CodePrometheus** [comment]
The CI I configured does not have `CheckStatus`, and my test [repo](https://github.com/CodePrometheus/skywalking-ruby/pull/3)'s CI is not found either. Is there any special configuration for the new repo.

**Comment by wu-sheng** [comment]
Because you made this. https://github.com/apache/skywalking-ruby/blob/main/.asf.yaml#L37

You need a dummy task to make CI check happy, and then you could remove and change the .asf.yaml

**Comment by CodePrometheus** [comment]
Thank you for pointing that out. I overlooked it, it's ok now.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
